# Loads default set of integrations. Do not remove.
# default_config:
config:
logbook:
sun:
my:
history:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
logger:
  default: info
  logs:
    pymodbus.logging: critical
    custom_components.modbus_local_gateway: debug

modbus:
  - name: modbus_hub
    type: rtuovertcp
    host: 127.0.0.1
    port: 502

    binary_sensors:
      - name: binary_sensor1
        address: 100
