#!/usr/bin/zsh
set -e
pip install pre-commit
uv venv --clear --seed --link-mode=copy
uv pip install -r requirements-dev.txt --link-mode=copy

if ! grep -q "source /workspaces/modbus_local_gateway/.venv/bin/activate" ~/.zshrc; then
    cat <<EOF >> ~/.zshrc
if [ -e /workspaces/modbus_local_gateway/.venv/bin/activate ]; then
    source /workspaces/modbus_local_gateway/.venv/bin/activate
fi
EOF
fi
