#!/usr/bin/zsh
set -e
pip install pre-commit
uv venv
uv pip install -r requirements-dev.txt --link-mode=copy

cat <<EOF >> ~/.zshrc
if [ -e /workspaces/modbus_local_gateway/.venv/bin/activate ]; then
    source /workspaces/modbus_local_gateway/.venv/bin/activate
fi
EOF
