name: Linting

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Register problem matchers
        run: |
          echo "::add-matcher::.github/workflows/matchers/yamllint.json"
          echo "::add-matcher::.github/workflows/matchers/check-json.json"
          echo "::add-matcher::.github/workflows/matchers/check-executables-have-shebangs.json"
          echo "::add-matcher::.github/workflows/matchers/codespell.json"

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: pip

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm

      - name: Install Python dependencies
        run: |
          python -m venv .venv
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install -r requirements_all.txt

      - name: Install Prettier dependencies
        run: npm ci

      - name: Run prek
        run: .venv/bin/prek run --all-files
